### ISSUE TITLE
Support commands in PR comments

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/leeroy-pull-request-builder#3]
[Jenkins GitHub PR Builder](https://github.com/janinko/ghprb) supports rerunning the build by adding a PR comment with the phrase `retest this please`.

Maybe other GitHub PR hooks (for Travis, Appveyor, etc.) provide a similar feature? If so, find out if there's a "standard" command and implement support for it.

**Comment by jacobcarpenter** [comment]
rebuild this please

**Comment by bgrainger** [comment]
`rebuild this` is now supported as a command.
